# Generated by Django 4.2.16 on 2025-06-30 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalAnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('analysis_results', models.JSONField(default=dict)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Análisis Fiscal',
                'verbose_name_plural': 'Sesiones de Análisis Fiscal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFiscalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_dependents', models.BooleanField(default=False)),
                ('dependents_count', models.PositiveIntegerField(default=0)),
                ('has_health_insurance', models.BooleanField(default=False)),
                ('has_mortgage', models.BooleanField(default=False)),
                ('has_afc_account', models.BooleanField(default=False)),
                ('prefers_conservative_analysis', models.BooleanField(default=True)),
                ('wants_optimization_suggestions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Fiscal de Usuario',
                'verbose_name_plural': 'Perfiles Fiscales de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='FiscalOptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('potential_saving', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('effort_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], default='medium', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('is_implemented', models.BooleanField(default=False)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='fiscal.fiscalanalysissession')),
            ],
            options={
                'verbose_name': 'Recomendación de Optimización',
                'verbose_name_plural': 'Recomendaciones de Optimización',
                'ordering': ['-priority', '-potential_saving'],
            },
        ),
    ]
