# Generated by Django 4.2.16 on 2025-07-01 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('declarations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('template_type', models.CharField(max_length=50, verbose_name='Tipo de plantilla')),
                ('template_content', models.TextField(verbose_name='Contenido de la plantilla')),
                ('variables', models.JSONField(default=list, verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='Nombre original del archivo')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('file_type', models.CharField(choices=[('exogena_report', 'Información Exógena'), ('income_certificate', 'Certificado de Ingresos'), ('withholding_certificate', 'Certificado de Retenciones'), ('bank_certificate', 'Certificado Bancario'), ('health_invoice', 'Factura de Salud'), ('education_invoice', 'Factura de Educación'), ('mortgage_certificate', 'Certificado de Crédito Hipotecario'), ('pension_certificate', 'Certificado de Pensiones'), ('dependents_proof', 'Prueba de Dependientes'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de documento')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME')),
                ('storage_path', models.CharField(help_text='Ruta en Google Cloud Storage', max_length=500, verbose_name='Ruta de almacenamiento')),
                ('storage_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de descarga')),
                ('upload_status', models.CharField(choices=[('pending', 'Pendiente'), ('uploading', 'Subiendo'), ('uploaded', 'Subido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado de carga')),
                ('processed_data', models.JSONField(blank=True, default=dict, help_text='Datos extraídos del documento', verbose_name='Datos procesados')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de procesamiento')),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de procesamiento')),
                ('processing_errors', models.JSONField(blank=True, default=list, verbose_name='Errores de procesamiento')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('checksum', models.CharField(blank=True, max_length=64, null=True, verbose_name='Checksum SHA256')),
                ('encrypted', models.BooleanField(default=True, verbose_name='Encriptado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Etiquetas')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='declarations.declaration', verbose_name='Declaración')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['declaration', 'file_type'], name='documents_d_declara_71c960_idx'), models.Index(fields=['upload_status'], name='documents_d_upload__3e86b8_idx'), models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx')],
            },
        ),
    ]
