# Generated by Django 4.2.16 on 2025-06-19 20:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(help_text='Año gravable de la declaración', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)])),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('completed', 'Completada'), ('paid', 'Pagada'), ('error', 'Error')], default='draft', max_length=20)),
                ('summary_data', models.JSONField(blank=True, help_text='Resumen de ingresos, retenciones e impuestos calculados', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Declaración de Renta',
                'verbose_name_plural': 'Declaraciones de Renta',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Nombre del archivo', max_length=255)),
                ('original_filename', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('file_type', models.CharField(choices=[('exogena_report', 'Información Exógena'), ('income_certificate', 'Certificado de Ingresos'), ('deduction_invoice', 'Soporte de Deducción'), ('bank_certificate', 'Certificado Bancario'), ('medical_invoice', 'Factura Médica'), ('education_invoice', 'Factura Educación'), ('mortgage_certificate', 'Certificado Hipotecario'), ('pension_certificate', 'Certificado Pensiones'), ('other', 'Otro')], max_length=50)),
                ('storage_path', models.CharField(help_text='Ruta en Google Cloud Storage', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('upload_status', models.CharField(choices=[('pending', 'Pendiente'), ('uploaded', 'Subido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('error', 'Error')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_data', models.JSONField(blank=True, help_text='Datos extraídos del documento', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.declaration')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del concepto', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Nombre del concepto', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('rentas_trabajo', 'Rentas de Trabajo'), ('rentas_capital', 'Rentas de Capital'), ('rentas_no_laborales', 'Rentas No Laborales'), ('retenciones', 'Retenciones'), ('otros', 'Otros')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concepto Fiscal',
                'verbose_name_plural': 'Conceptos Fiscales',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Log de Procesamiento',
                'verbose_name_plural': 'Logs de Procesamiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
