# Generated by Django 4.2.23 on 2025-06-21 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declarations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('template_type', models.CharField(max_length=50, verbose_name='Tipo de plantilla')),
                ('template_content', models.TextField(verbose_name='Contenido de la plantilla')),
                ('variables', models.JSONField(default=list, verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='declaration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='processinglog',
            name='document',
        ),
        migrations.DeleteModel(
            name='TaxConcept',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='document',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='document',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='document',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Checksum SHA256'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='document',
            name='encrypted',
            field=models.BooleanField(default=True, verbose_name='Encriptado'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_file_name',
            field=models.CharField(default='unknown.txt', max_length=255, verbose_name='Nombre original del archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='processing_errors',
            field=models.JSONField(blank=True, default=list, verbose_name='Errores de procesamiento'),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de descarga'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Etiquetas'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='document',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='declarations.declaration', verbose_name='Declaración'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('exogena_report', 'Información Exógena'), ('income_certificate', 'Certificado de Ingresos'), ('withholding_certificate', 'Certificado de Retenciones'), ('bank_certificate', 'Certificado Bancario'), ('health_invoice', 'Factura de Salud'), ('education_invoice', 'Factura de Educación'), ('mortgage_certificate', 'Certificado de Crédito Hipotecario'), ('pension_certificate', 'Certificado de Pensiones'), ('dependents_proof', 'Prueba de Dependientes'), ('other', 'Otro')], max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos extraídos del documento', verbose_name='Datos procesados'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de procesamiento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de procesamiento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='storage_path',
            field=models.CharField(help_text='Ruta en Google Cloud Storage', max_length=500, verbose_name='Ruta de almacenamiento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('uploading', 'Subiendo'), ('uploaded', 'Subido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado de carga'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['declaration', 'file_type'], name='documents_d_declara_71c960_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload_status'], name='documents_d_upload__3e86b8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_d_created_3b0a51_idx'),
        ),
        migrations.DeleteModel(
            name='Declaration',
        ),
        migrations.DeleteModel(
            name='ProcessingLog',
        ),
    ]
