# Generated by Django 4.2.16 on 2025-07-01 03:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo para identificar esta declaración', max_length=255, verbose_name='Título de la declaración')),
                ('fiscal_year', models.IntegerField(help_text='Año gravable de la declaración', verbose_name='Año fiscal')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('completed', 'Completada'), ('paid', 'Pagada'), ('error', 'Error')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si esta declaración está activa (soft delete)', verbose_name='Activa')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Ingresos totales')),
                ('total_withholdings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Retenciones totales')),
                ('preliminary_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Impuesto preliminar')),
                ('declaration_data', models.JSONField(blank=True, default=dict, help_text='Datos estructurados de la declaración procesada', verbose_name='Datos de la declaración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('processing_errors', models.JSONField(blank=True, default=list, verbose_name='Errores de procesamiento')),
                ('processing_warnings', models.JSONField(blank=True, default=list, verbose_name='Advertencias de procesamiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Declaración',
                'verbose_name_plural': 'Declaraciones',
                'ordering': ['-fiscal_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_nit', models.CharField(max_length=20, verbose_name='NIT del tercero')),
                ('third_party_name', models.CharField(max_length=255, verbose_name='Nombre del tercero')),
                ('concept_code', models.CharField(help_text='Código del concepto según la DIAN', max_length=10, verbose_name='Código del concepto')),
                ('concept_description', models.CharField(max_length=255, verbose_name='Descripción del concepto')),
                ('income_type', models.CharField(choices=[('salary', 'Salarios'), ('honorarios', 'Honorarios'), ('services', 'Servicios'), ('dividends', 'Dividendos'), ('interests', 'Intereses'), ('rental', 'Arrendamientos'), ('other', 'Otros')], default='other', max_length=20, verbose_name='Tipo de ingreso')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor bruto')),
                ('withholding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Retención practicada')),
                ('tax_schedule', models.CharField(blank=True, choices=[('labor', 'Rentas de Trabajo'), ('capital', 'Rentas de Capital'), ('non_labor', 'Rentas No Laborales'), ('pensions', 'Pensiones'), ('dividends', 'Dividendos y Participaciones')], help_text='Clasificación según cédulas del Estatuto Tributario', max_length=20, null=True, verbose_name='Cédula tributaria')),
                ('period', models.CharField(blank=True, help_text='Período del ingreso (ej: 2024-01)', max_length=10, null=True, verbose_name='Período')),
                ('is_deductible', models.BooleanField(default=False, verbose_name='Es deducible')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='declarations.declaration', verbose_name='Declaración')),
            ],
            options={
                'verbose_name': 'Registro de Ingreso',
                'verbose_name_plural': 'Registros de Ingresos',
                'ordering': ['third_party_name', 'concept_code'],
                'indexes': [models.Index(fields=['declaration', 'income_type'], name='declaration_declara_8b5a7f_idx'), models.Index(fields=['tax_schedule'], name='declaration_tax_sch_649dfa_idx'), models.Index(fields=['concept_code'], name='declaration_concept_e8de05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['user', '-fiscal_year'], name='declaration_user_id_4a4c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['status'], name='declaration_status_e13135_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['created_at'], name='declaration_created_d5bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['user', 'status'], name='declaration_user_id_386fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='declaration',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='declaration_user_id_57c4aa_idx'),
        ),
    ]
